/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/sf_girl.glb 
Author: Stan (https://sketchfab.com/Stas_SayHallo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sf-girl-a219070284e64ddd8a51f69c207cc81b
Title: SF_Girl
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sf_girl.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={198.671}>
          <group name="ad56d3eb10d44fb68878825e9765ea23fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="rig" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_117" position={[0, -0.098, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                    <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.SF_Body} skeleton={nodes.Object_118.skeleton} />
                    <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.SF_Cloth} skeleton={nodes.Object_119.skeleton} />
                    <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.SF_Eye} skeleton={nodes.Object_120.skeleton} />
                  </group>
                </group>
                <group name="body_low" position={[0, -0.098, 0]} rotation={[-Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sf_girl.glb')
