/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/sunglass.glb 
Author: horse_water (https://sketchfab.com/keitamamizu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sunglass-sketchfab-weekly-challenge-2023-39159224a5584595955f601711668cce
Title: Sunglass - Sketchfab Weekly Challenge 2023
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sunglass.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[81.78, -46.559, -19.413]} rotation={[-Math.PI / 2, 0, 0.649]} scale={39.698}>
          <mesh geometry={nodes.Kazari_Silver_0.geometry} material={materials.Silver} />
          <mesh geometry={nodes.Kazari_Silver_0_1.geometry} material={materials.Silver} />
          <mesh geometry={nodes.Kazari_Silver_0_2.geometry} material={materials.Silver} />
        </group>
        <mesh geometry={nodes.LensFrame_Frame_0.geometry} material={materials.Frame} position={[45.504, 0, 0.277]} scale={34.304} />
        <mesh geometry={nodes.Bridge_Frame_0.geometry} material={materials.Frame} position={[0, 6.902, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.857, 3.358, 4.149]} />
        <mesh geometry={nodes.EarFrame_Frame_0.geometry} material={materials.Frame} position={[78.944, 7.799, -3.931]} rotation={[-Math.PI / 2, 0, 0]} scale={6.867} />
        <mesh geometry={nodes.Joint_Frame_0.geometry} material={materials.Frame} position={[78.944, 7.799, -3.931]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.771, 1.771, 2.537]} />
        <mesh geometry={nodes.NosePad_Nose_0.geometry} material={materials.Nose} position={[13.975, -5.2, -4.183]} rotation={[1.715, 0.463, -0.767]} scale={[2.191, 0.729, 5.584]} />
        <mesh geometry={nodes.NoseJoint_Frame_0.geometry} material={materials.Frame} position={[9.979, -0.107, 0.386]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Lens_Glass_0.geometry} material={materials.Glass} position={[45.504, 0, 0.277]} scale={34.304} />
        <mesh geometry={nodes.JewelStone_Jewel001_0.geometry} material={materials['Jewel.001']} position={[0, 7.194, 3.688]} scale={1.973} />
        <mesh geometry={nodes.JewelStone001_Jewel002_0.geometry} material={materials['Jewel.002']} position={[5.093, 6.696, 3.221]} rotation={[0, 0.172, 0]} scale={1.377} />
        <mesh geometry={nodes.JewelStone002_Jewel003_0.geometry} material={materials['Jewel.003']} position={[9.466, 5.921, 2.308]} rotation={[0, 0.252, 0]} scale={0.831} />
        <mesh geometry={nodes.JewelStone003_Jewel001_0.geometry} material={materials['Jewel.001']} position={[16.276, 12.193, 1.908]} scale={1.973} />
        <mesh geometry={nodes.JewelStone004_Jewel002_0.geometry} material={materials['Jewel.002']} position={[17.989, 16.956, 1.9]} scale={1.457} />
        <mesh geometry={nodes.JewelStone005_Jewel003_0.geometry} material={materials['Jewel.003']} position={[19.719, 20.055, 1.963]} scale={0.824} />
        <mesh geometry={nodes.BridgeDeco_Gold_0.geometry} material={materials.Gold} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.LensFrameDecoUpper_Gold_0.geometry} material={materials.Gold} position={[45.504, 0, 0.277]} rotation={[0, 0, 0.473]} scale={34.304} />
        <mesh geometry={nodes.LensFrameDecoSide_Gold_0.geometry} material={materials.Gold} position={[66.85, -21.962, 2.235]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.JewelStone006_Jewel001_0.geometry} material={materials['Jewel.001']} position={[37, -31.136, 1.908]} rotation={[0, 0, -1.631]} scale={1.973} />
        <mesh geometry={nodes.JewelStone007_Jewel002_0.geometry} material={materials['Jewel.002']} position={[42.191, -32.177, 1.9]} rotation={[0, 0, -1.631]} scale={1.457} />
        <mesh geometry={nodes.JewelStone008_Jewel003_0.geometry} material={materials['Jewel.003']} position={[46.2, -32.614, 1.963]} rotation={[0, 0, -1.631]} scale={0.824} />
        <mesh geometry={nodes.WingFrame_Gold_0.geometry} material={materials.Gold} position={[82.626, 4.834, -1.051]} rotation={[-Math.PI / 2, 0, 0.856]} scale={100} />
        <mesh geometry={nodes.Wing_Wing_0.geometry} material={materials.Wing} position={[82.626, 4.834, -1.051]} rotation={[-Math.PI / 2, 0, 0.856]} scale={100} />
        <mesh geometry={nodes.WingDeco_Gold_0.geometry} material={materials.Gold} position={[82.626, 4.834, -1.051]} rotation={[0, 0.856, 0]} scale={1.791} />
        <mesh geometry={nodes.Chain_Silver_0.geometry} material={materials.Silver} position={[81.739, 3.124, -19.276]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={4.428} />
        <mesh geometry={nodes.ChainJoint_Silver_0.geometry} material={materials.Silver} position={[81.646, 7.325, -19.507]} scale={[3.952, 3.952, 3.417]} />
        <mesh geometry={nodes.Ball_Ball_0.geometry} material={materials.Ball} position={[81.788, -73.74, -19.302]} rotation={[-Math.PI / 2, 0, 0]} scale={56.102} />
        <mesh geometry={nodes.BallJoint_Gold_0.geometry} material={materials.Gold} position={[81.78, -68.277, -19.302]} rotation={[-Math.PI / 2, 0, 0]} scale={56.102} />
        <mesh geometry={nodes.TearDropJewel_TearDrop_0.geometry} material={materials.TearDrop} position={[82.076, -102.195, -19.966]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.756, 5.756, 11.457]} />
        <mesh geometry={nodes.TearDropJoint_Gold_0.geometry} material={materials.Gold} position={[82.076, -101.847, -19.966]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.756, 5.756, 11.457]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sunglass.glb')
